spring.application.name=hr-backend
server.port=8087

spring.datasource.url=jdbc:postgresql://localhost:5432/hr_management
spring.datasource.username=hr_uuser
spring.datasource.password=hr123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/hr-realm

# Spring multipart file upload configurations
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB